FROM mcr.microsoft.com/mssql/server:2019-latest

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=[DB_PASSWORD]

COPY ./setup-db.sql .

CMD (sleep 10s && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P [DB_PASSWORD] -i ./setup-db.sql) & /opt/mssql/bin/sqlservr