version: "3.7"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: webapp
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile-DB
    image: db
    ports:
      - "1433:1433"